name: '[CI] Build WASM'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - run: docker build -t grad_aff_wasm_sdk .
      name: Build SDK image
    - run: docker run --rm -v ${PWD}:/usr/src/app grad_aff_wasm_sdk make
      name: Run make within SDK image
    - uses: actions/upload-artifact@v2
      with:
        name: grad_aff_wasm
        path: release
